### ISSUE TITLE
Recopilar datos ponentes Xornadas Técnicas 2014

### ISSUE THREAD

**Issue by lorenzogrv** [laconbass/expomar.com#11]
Hay certos datos que non se puideron engadir ao contido debido á falta dos mesmos ou erros dalgún tipo.

Datos que faltan organizados por ponentes:
- [ ] **Victor Jiménez Fenández**
  - [ ] Fotografía
  - [ ] CV
  - [ ] sinopse do contido da presentación
- [ ] **Mª do Carme García Negro**
  - [ ] sinopse do contido da presentación
- [ ] **Andrés Hermida Trastoy**
  - [ ] fotografía
  - [ ] CV - Arquivo corrompido - #10 
- [ ] **Torcuato Teixeira Valoria**
  - [ ] CV - Codificación errónea ou arquivo corrompido? #10 
  - [ ] presentación en powerpoint (#6)
  - [ ] sinopse do contido da presentación
- [ ] **Ernesto Penas Lado**
  - [ ] CV
  - [ ] sinopse do contido da presentación
- [ ] **Antonio Basanta Fernández**
  - [ ] fotografía
  - [ ] sinopse do contido da presentación
